-- Fase 3: deduplicar por fila física en EVENTO (misma CURP en varios eventos).
ALTER TABLE PUI_COINCIDENCIAS ADD (EVENTO_ROWID VARCHAR2(18));

CREATE INDEX IDX_PUI_COINCID_F3_ROWID ON PUI_COINCIDENCIAS (ID_REPORTE, FASE_BUSQUEDA, EVENTO_ROWID);
