CREATE TABLE PUI_JWT_TOKENS (
    JTI         VARCHAR2(128)    NOT NULL,
    EXP_AT      TIMESTAMP WITH TIME ZONE NOT NULL,
    USADO       NUMBER(1)        DEFAULT 1 NOT NULL,
    USED_AT     TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_AT  TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PUI_JWT_TOKENS PRIMARY KEY (JTI),
    CONSTRAINT CK_PUI_JWT_TOKENS_USADO CHECK (USADO IN (0, 1))
);

CREATE INDEX IDX_PUI_JWT_TOKENS_EXP_AT ON PUI_JWT_TOKENS (EXP_AT);
