CREATE TABLE PUI_REPORTES_ACTIVOS (
    ID_REPORTE         VARCHAR2(75)      NOT NULL,
    CURP               VARCHAR2(18)      NOT NULL,
    INSTITUCION_ID     VARCHAR2(13),
    CRITERIO_NOMBRE    VARCHAR2(100),
    PRIMER_APELLIDO    VARCHAR2(50),
    SEGUNDO_APELLIDO   VARCHAR2(50),
    RFC_CRITERIO       VARCHAR2(13),
    ESTADO             VARCHAR2(20)      NOT NULL,
    ES_PRUEBA          NUMBER(1)         DEFAULT 0 NOT NULL,
    FECHA_ACTIVACION   TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    ULTIMA_BUSQUEDA    TIMESTAMP,
    FECHA_DESACTIVACION TIMESTAMP,
    ACTIVO             NUMBER(1)         DEFAULT 1 NOT NULL,
    CONSTRAINT PK_PUI_REPORTES_ACTIVOS PRIMARY KEY (ID_REPORTE),
    CONSTRAINT CK_PUI_RPT_ACTIVO CHECK (ACTIVO IN (0,1)),
    CONSTRAINT CK_PUI_RPT_PRUEBA CHECK (ES_PRUEBA IN (0,1))
);

CREATE INDEX IDX_PUI_RPT_ACTIVO ON PUI_REPORTES_ACTIVOS (ACTIVO, ESTADO);
CREATE INDEX IDX_PUI_RPT_CURP ON PUI_REPORTES_ACTIVOS (CURP);
